import type { Metadata } from "next";
import { Inter, Michroma } from "next/font/google";
import Gyparody from 'next/font/local';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gyparody = Gyparody({
  src: '../public/fonts/gyparody.ttf',
  variable: '--font-gyparody'
});

const michroma = Michroma({
  weight: "400",
  subsets: ["latin"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`
          ${inter.className}
          ${michroma.className}
          ${gyparody.className}`
        }>
          {children}
      </body>
    </html>
  );
}
